full names and working tagging
e-m-b-a/emba pull request #1061
Opened 2024-03-01 12:01 UTC by HoxhaEndri

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
The names of the cves are now full and consistent. The tags should also be consistent now.
Tested with the first 50 pages.

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)? If possible add a screenshot.**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

2024-03-01 12:13 UTC, m-1-k-3 commented
Please add your name to the Authors

2024-03-01 14:27 UTC, HoxhaEndri commented
> looks as it gets out of sync:
> 
> ```
> [*] Generating list of URLs of packetstorm advisory page 1046
> [+] Found PoC for CVE-2012-1664 in advisory osCmax 2.5.0 Cross Site Scripting SQL Injection / https://packetstormsecurity.com/files/111559/osCmax-2.5.0-Cross-Site-Scripting-SQL-Injection.html
> [+] Found PoC for CVE-2012-1665 in advisory osCmax 2.5.0 Cross Site Scripting SQL Injection / https://packetstormsecurity.com/files/111559/osCmax-2.5.0-Cross-Site-Scripting-SQL-Injection.html
> [+] Found PoC for CVE-2012-1671 in advisory phpPaleo 4.8b156 Local File Inclusion / https://packetstormsecurity.com/files/111545/phpPaleo-4.8b156-Local-File-Inclusion.html
> [+] Found PoC for CVE-2012-1672 in advisory Pluck 4.7 Cross Site Request Forgery / https://packetstormsecurity.com/files/111582/Pluck-4.7-Cross-Site-Request-Forgery.html
> ```
> 
> If I go to site [1046](https://packetstormsecurity.com/files/tags/exploit/page1046) I can see the Pluck 4.7 CSRF entry ... but it has no CVE identifier:
> 

I will look into it

2024-03-18 09:02 UTC, m-1-k-3 requested changes
just two notes for review

2024-03-18 09:02 UTC, m-1-k-3 commented on helpers/packet_storm_crawler.sh
> +NUMBER_OF_PAGES=$(lynx -dump "${URL}" | grep -E "Page 1 of " | sed -r 's/.*of ([0-9])\,/\1/')
should we do a check to ensure we have a number of pages here?
if ! [[ "${NUMBER_OF_PAGES}" -gt 0 ]]; then
  echo "[-] Number of pages could not be extracted ... exit now"
  exit 1
fi

2024-03-18 09:17 UTC, HoxhaEndri commented on .github/workflows/packet_storm_crawler.yml
> +    if: github.repository_owner == 'HoxhaEndri'
ah yes

2024-03-18 09:18 UTC, HoxhaEndri commented on helpers/packet_storm_crawler.sh
> +NUMBER_OF_PAGES=$(lynx -dump "${URL}" | grep -E "Page 1 of " | sed -r 's/.*of ([0-9])\,/\1/')
We could, but the number of pages is always present

2024-03-18 09:19 UTC, m-1-k-3 commented on helpers/packet_storm_crawler.sh
> +NUMBER_OF_PAGES=$(lynx -dump "${URL}" | grep -E "Page 1 of " | sed -r 's/.*of ([0-9])\,/\1/')
Please include such a quick check.

2024-03-18 09:31 UTC, HoxhaEndri commented on helpers/packet_storm_crawler.sh
> +NUMBER_OF_PAGES=$(lynx -dump "${URL}" | grep -E "Page 1 of " | sed -r 's/.*of ([0-9])\,/\1/')
done

2024-03-18 11:56 UTC, m-1-k-3 commented on .github/workflows/packet_storm_crawler.yml
> +    if: github.repository_owner == 'HoxhaEndri'
please fix for merge

2024-03-18 12:15 UTC, HoxhaEndri commented on .github/workflows/packet_storm_crawler.yml
> +    if: github.repository_owner == 'HoxhaEndri'
> please fix for merge

I thought I did it, but I forgot that it gets ignored by git.

2024-03-18 12:21 UTC, m-1-k-3 approved these changes

2024-03-18 12:21 UTC, m-1-k-3 commented
Thank you for fixing this script!

2024-03-18 12:21 UTC, merged