Fix missing kernel config analysis because of lKCONFIG_EXTRACTED/KCON…
e-m-b-a/emba pull request #1415
Opened 2024-12-19 17:32 UTC by chconil

Kernel configuration is not currently not detected, even when the creation is successful. This fixes it.
Feel free to edit the patch

2024-12-19 18:09 UTC, m-1-k-3 approved these changes
What a nasty refactoring bug. Thanks for fixing it!

2024-12-19 19:24 UTC, m-1-k-3 requested changes
looks as you are using tabs instead of spaces:

![image](https://github.com/user-attachments/assets/f22471e9-9df6-4d0f-b8d3-5f2994fd8ff8)

As we are using spaces could you please change this to use two spaces for a tab?

2024-12-19 19:47 UTC, chconil commented
> looks as you are using tabs instead of spaces:
> 
> ![image](https://private-user-images.githubusercontent.com/497520/397506320-f22471e9-9df6-4d0f-b8d3-5f2994fd8ff8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2Mzc5NDAsIm5iZiI6MTczNDYzNzY0MCwicGF0aCI6Ii80OTc1MjAvMzk3NTA2MzIwLWYyMjQ3MWU5LTlkZjYtNGQwZi1iOGQzLTVmMjk5NGZkOGZmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOVQxOTQ3MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYjgxOTdkMjJlOWVhNjljOWY3NjZjNmIyNDlmYzEzZmEyNTVjNjY3MTdlNzc3NDdlODIxZjcyOWQ3YWU1NzRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zeyXeuhZOgtLASn2sp6m-U0B3WQGiOv4fyBmXn0SYWA)
> 
> As we are using spaces could you please change this to use two spaces for a tab?

Weird, my editor should have catched that. Anyway, fixed ! :)

2024-12-20 09:50 UTC, m-1-k-3 approved these changes

2024-12-20 09:50 UTC, merged