Allow some firmware details as parameters
e-m-b-a/emba pull request #41
Opened 2021-01-22 13:38 UTC by m-1-k-3

It is possible to start emba with some additional parameters regarding the firmware under test:

```
Firmware details
-X [version]      Firmware version (double quote your input)
-Y [vendor]       Firmware vendor (double quote your input)
-Z [device]       Device (double quote your input)
-N [notes]        Testing notes (double quote your input)
```

This could result in the following emba startup command:

`sudo ./emba.sh -z -s -l ./logs_dir635 -f /home/m1k3/git-repos/testimages/testimages/testimages/DIR300B5_FW214WWB01.bin -X "2.14-b01" -Y "DLink" -Z "DIR 300 - Wlan router" -N "old firmware" -E`

Emba shows these details on startup:

![image](https://user-images.githubusercontent.com/497520/105497437-2093d400-5cbf-11eb-9383-52f8944cbb3a.png)

Additionally it gets respect in the aggregator:

![image](https://user-images.githubusercontent.com/497520/105497495-33a6a400-5cbf-11eb-85b9-4b94f5b61b88.png)

2021-01-22 14:57 UTC, p4cx requested changes

2021-01-22 14:57 UTC, p4cx commented on emba.sh
> +  print_output "" "no_log"
You can use `echo` instead of `print_output "" "no_log`

2021-01-22 14:57 UTC, p4cx commented on modules/F50_base_aggregator.sh
>      print_output ""
Here you can use `print_output "\\n-----------------------------------------------------------------\\n"`

2021-01-26 14:11 UTC, p4cx commented
Shellcheck fails here :(

2021-01-26 14:50 UTC, m-1-k-3 commented
this SC2001 drives me crazy ...

2021-01-27 06:42 UTC, p4cx reviewed
Code looks fine to me and will test functionality later.

2021-01-27 15:25 UTC, p4cx approved these changes

2021-01-27 15:25 UTC, merged