Cleanup
e-m-b-a/emba pull request #65
Opened 2021-03-08 18:00 UTC by p4cx

Add `-l` to `installer.sh`
Fix some small issues in installer

Rewrite `emba.sh`
To give modules higher prio in threaded run: Add `export THREAD_PRIO=1` to the modules. No need to set it to zero for 'normal' modules.

2021-03-14 15:13 UTC, m-1-k-3 requested changes

2021-03-14 15:13 UTC, m-1-k-3 commented on emba.sh
> +    sort_modules
after movin it to line 96 (right after the modules array gets populated) it works as expected

2021-03-15 07:08 UTC, p4cx commented on helpers/dependency_check.sh
> +          echo -e "$RED""    Missing docker - check your installation""$NC"
I thought it was clear that the installer should be used. Manual installation instructions shouldn't be required.

2021-03-15 07:08 UTC, p4cx commented on helpers/dependency_check.sh
> -      if [[ $ONLY_DEP -eq 0 ]] && [[ $FORCE -eq 0 ]] ; then
Same answer as above.

2021-03-15 07:09 UTC, p4cx commented on helpers/dependency_check.sh
> +    SYSTEM_TOOLS=("awk" "basename" "bash" "cat" "chmod" "chown" "cp" "cut" "date" "dirname" "dpkg-deb" "echo" "eval" "find" "grep" "head" "kill" "ln" "ls" "md5sum" "mkdir" "mknod" "modinfo" "mv" "net
bc isn't part of coreutils and therefore not a "system tool" as we understand it. You have to install it externally and therefore it's listed as external tool.

2021-03-15 07:37 UTC, m-1-k-3 commented on helpers/dependency_check.sh
> +    SYSTEM_TOOLS=("awk" "basename" "bash" "cat" "chmod" "chown" "cp" "cut" "date" "dirname" "dpkg-deb" "echo" "eval" "find" "grep" "head" "kill" "ln" "ls" "md5sum" "mkdir" "mknod" "modinfo" "mv" "net
a ok, so this is not optional and "not optional". Everything is mandatory ... then it is fine for me

2021-03-15 07:38 UTC, m-1-k-3 commented on helpers/dependency_check.sh
> +          echo -e "$RED""    Missing docker - check your installation""$NC"
then include a note to run the command "sudo ./installer" for fixing everything and please include a link to our wiki: https://github.com/e-m-b-a/emba/wiki/Installation

2021-03-15 14:41 UTC, m-1-k-3 approved these changes

2021-03-15 14:41 UTC, merged