Much cleaner OS detection
e-m-b-a/emba pull request #75
Opened 2021-03-16 11:28 UTC by m-1-k-3

Improved the OS detection from the final aggregator. Now it also uses the version details from the CVE module.

2021-03-18 20:16 UTC, p4cx commented
I don't know if this happens here or in the other (already merged , because most of it was already in the master branch,) pr #74 but it seems to count some exploits multiple time: 

![image](https://user-images.githubusercontent.com/17053360/111691928-1d384700-882f-11eb-8e61-d8603c29179c.png)

2021-03-18 20:20 UTC, p4cx requested changes
Please fix the problem with the multiple counted exploits / CVEs, otherwise it's a good job!

2021-03-19 07:02 UTC, m-1-k-3 commented
yes ... this is already fixed in my local repo. I need to push it :)

2021-03-19 08:25 UTC, m-1-k-3 commented
![image](https://user-images.githubusercontent.com/497520/111751592-fad91480-8894-11eb-9cde-b36c151dba88.png)

2021-03-19 09:35 UTC, p4cx commented
What's about this line?

![111751592-fad91480-8894-11eb-9cde-b36c151dba88](https://user-images.githubusercontent.com/17053360/111760106-a044b600-889e-11eb-8099-6c9bc4ea9562.png)

2021-03-19 09:39 UTC, m-1-k-3 commented
I have seen it also. I will check this one in a new pull next week

2021-03-19 12:34 UTC, m-1-k-3 commented
Now it looks much better

![image](https://user-images.githubusercontent.com/497520/111780492-c75bb180-88b7-11eb-9478-37c097f7a0bf.png)

Probably we should sort it in the next step. But lets do it next week ;)

2021-03-19 12:39 UTC, p4cx approved these changes

2021-03-19 12:40 UTC, merged