Fix -s switch
e-m-b-a/emba pull request #78
Opened 2021-03-22 07:39 UTC by p4cx

Firmware path has to be absolute to allow shortening with `-s`.

2021-03-22 10:15 UTC, m-1-k-3 requested changes
I have done a quick test and yes we need to change this.

But on a quick check I have seen that it also brings troubles on firmwares we are going to extract with emba.

For example we now have a path in our logs like the following:
/DIR300B5_FW214WWB01.bin_binwalk_emba/_DIR300B5_FW214WWB01.bin.extracted/squashfs-root/usr/sbin/rt3052esw
wich is somewhere in 
/home/m1k3/git-repos/emba_forked/logs_test1/extractor

So, nobody knows where to look at. 
Probably we should take the path starting from the current emba location?
./logs_test1/extractor/DIR300B5_FW214WWB01.bin_binwalk_emba/_DIR300B5_FW214WWB01.bin.extracted/squashfs-root/usr/sbin/rt3052esw

2021-03-22 14:27 UTC, p4cx commented
![image](https://user-images.githubusercontent.com/17053360/112005462-12c5c800-8b23-11eb-9d67-5a186efeeea1.png)

2021-03-22 15:09 UTC, m-1-k-3 commented
I will do a test tomorrow

2021-03-23 14:08 UTC, m-1-k-3 requested changes
it is mostrly working:

└─$ sudo ./emba.sh -s -l ./logs_testing1 -f ./logs_testing/extractor/DIR300B5_FW214WWB01.bin_binwalk_emba/

=> root directory is a sub directory of the used firmware directory.

![image](https://user-images.githubusercontent.com/497520/112159280-44a16200-8be9-11eb-8f85-b5fadbf0449d.png)

so, the output for the paths should be something like this:

./logs_testing/extractor/DIR300B5_FW214WWB01.bin_binwalk_emba/_DIR300B5_FW214WWB01.bin.extracted/squashfs-root/usr/sbin/wps

2021-03-24 10:21 UTC, p4cx commented
Whether you use a firmware binary file or an already extracted filesystem, the short path (`-s`) will be `./[your_log_path]/firmware/[firmware_dir]`.

2021-03-24 14:51 UTC, m-1-k-3 requested changes
I think after the small changes we are ready to go

2021-03-24 14:51 UTC, m-1-k-3 commented on modules/P05_firmware_bin_extractor.sh
>    print_output "[*] Extracting firmware to directory $OUTPUT_DIR_binwalk"
we have to adjust also line 235 and 238 otherwise the ipk and deb extractor will fail

2021-03-24 14:51 UTC, m-1-k-3 commented on emba.sh
> +    FIRMWARE_PATH="$FIRMWARE_PATH_CP""/""$(basename "$FIRMWARE_PATH")"
I think we are having an issue with our OUTPUT_DIR which is only feeded in module P05 and we are using it in S09. We need to set it up here to ensure it is setup correctly. Include as easy fix 
OUTPUT_DIR="$FIRMWARE_PATH_CP"

2021-03-25 12:08 UTC, m-1-k-3 approved these changes

2021-03-25 12:08 UTC, m-1-k-3 commented
tests are looking good. Going to merge it now

2021-03-25 12:08 UTC, merged